l_spanish:
SETTINGS_PAGE_GRAPHICS:0 "Grafica"
SETTINGS_PAGE_GAME:0 "Gioco"
SETTINGS_PAGE_SYSTEM:0 "Sistema"
SETTINGS_PAGE_CONTROLS:0 "Comandi"
SETTINGS_PAGE_EDITOR:0 "Editor"
SETTINGS_PAGE_INTERFACE:0 "Interfaccia"
SETTINGS_PAGE_AUDIO:0 "Audio"
SETTINGS_CATEGORY_SCREEN:0 "Schermo"
SETTINGS_CATEGORY_QUALITY:0 "Qualità"
OPTION_EASY:0 "Facile"
OPTION_NORMAL:0 "Normale"
OPTION_HARD:0 "Difficile"
OPTION_NEVER:0 "Mai"
OPTION_MONTHLY:0 "Ogni mese"
OPTION_HALFYEAR:0 "Ogni metà anno"
OPTION_YEARLY:0 "Ogni anno"
OPTION_FIVE_YEAR:0 "Ogni cinque anni"
OPTION_NO_AUTOSAVE:0 "Non salvare automaticamente"
SETTINGS_CATEGORY_ACCOUNT:0 "Account"
SETTINGS_CATEGORY_SYSTEM:0 "Sistema"
SETTINGS_CATEGORY_CONTROLS:0 "Comandi"
SETTINGS_CATEGORY_CAMERA:0 "Camera"
SETTINGS_CATEGORY_AUDIO:0 "Audio"
SETTINGS_CATEGORY_GUI:0 "GUI"
SETTINGS_CATEGORY_INPUT_BINDINGS:0 "Tasti assegnati"
DISCARD:0 "Scarta"
APPLY:0 "Applica"
SAVE_AND_CLOSE:0 "OK"
SETTINGS:0 "Impostazioni"
REQUIRES_RESTART:0 "Richiede il riavvio"
REQUIRE_RESTART_DESCRIPTION:0 "Alcune impostazioni non avranno effetto finché non riavvierai il gioco."
SETTINGS_INPUT_REMAP_INPUT:0 "Riassegna"
SETTINGS_INPUT_CONFIRM:0 "Conferma"
SETTINGS_INPUT_CANCEL:0 "Annulla"
SETTINGS_INPUT_CLEAR:0 "Azzera"
SETTINGS_INPUT_SAVE_INPUT_PROFILE:0 "Salva il Profilo"
SETTINGS_INPUT_LOAD_INPUT_PROFILE:0 "Carica il Profilo"
SETTINGS_INPUT_RESET_INPUT_PROFILE:0 "Resetta ai valori Predefiniti"
SETTINGS_INPUT_BINDING_TEXT:0 "Assegna un tasto per l'azione '$INPUT_ACTION$':\n\n$INPUT_NAME$"
SETTINGS_INPUT_BINDING_WARNING_TEXT:0 "Attenzione: questo tasto è già all’azione '$INPUT_ACTION$'!\nPremendo su '$SETTINGS_INPUT_CONFIRM$' cancellerai la precedente assegnazione"
